apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: surfersweb-surferslookout.com
spec:
  virtualhost:
    fqdn: surferslookout.com
  routes:
    services:
    - name: surfersweb-00001
      port: 80
      requestHeadersPolicy:
        set:
        - name: Knative-Serving-Namespace
          value: alpha
        - name: Knative-Serving-Revision
          value: surfersweb-00001
      weight: 100
    timeoutPolicy:
      idle: infinity
      response: infinity
  - conditions:
    enableWebsockets: true
    permitInsecure: true
    requestHeadersPolicy:
      set:
      - name: K-Network-Hash
        value: a2604671b402deaa90eb90983e5d025df4caf081ec3ae91dd8a0fda70eec0c13
    retryPolicy:
      count: 2
      retryOn:
      - cancelled
      - connect-failure
      - refused-stream
      - resource-exhausted
      - retriable-status-codes
      - reset
