apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: python
spec:
  params:
    - name: source-url                       
    - name: source-revision                  
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: python
            script: |-
              # running python pytest
              echo "ls without root"
              ls
              echo "python version"
              python version
              echo "find requirements"
              find . -name requirements.txt
              pip install -r /workspace/requirements.txt
              python -m pytest

              