apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: surfersweb
spec:
  acceptedServiceBindings:
  - name: mysql
    types:
    - mysql
  build:
    buildpacks: {}
    path: ../..
  ports:
  - name: main
    port: 8080
